version: "3.7"

networks:
  app_net:
    external: true

services:
  redis-node1:
    image: bitnami/redis-cluster:latest
    container_name: redis-node1
    hostname: redis-node1
    ports:
      - 16379:6379
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node1 redis-node2 redis-node3
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/redis-cluster/node1/data:/bitnami/redis/data

  redis-node2:
    image: bitnami/redis-cluster:latest
    container_name: redis-node2
    hostname: redis-node2
    ports:
      - 16380:6379
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node1 redis-node2 redis-node3
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/redis-cluster/node2/data:/bitnami/redis/data

  redis-node3:
    image: bitnami/redis-cluster:latest
    container_name: redis-node3
    hostname: redis-node3
    ports:
      - 16381:6379
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node1 redis-node2 redis-node3
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/redis-cluster/node3/data:/bitnami/redis/data
