version: "3.7"

networks:
  app_net:
    external: true

services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    container_name: dnsmasq
    ports:
      - 53:53/udp
      - 5380:8080
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - HTTP_USER=root
      - HTTP_PASS=123456
    volumes:
      - ./conf/dnsmasq.conf:/etc/dnsmasq.conf
      - ./conf/resolv.conf:/etc/resolv.conf
