version: "3.7"

networks:
  app_net:
    external: true

services:
  java:
    build:
      context: .
    working_dir: /code
    container_name: java
    # ports:
    #   - 8000:8000
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /code:/code
    stdin_open: true
    tty: true
