version: "3.7"

networks:
  app_net:
    external: true

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=123456
    volumes:
      - /data/gitea/data:/data
    depends_on:
      - mysql

  mysql:
    container_name: mysql:8
    ports:
      - 3306:3306
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=gitea
    volumes:
      - /data/mysql/data:/var/lib/mysql
