version: "3.7"

networks:
  app_net:
    external: true

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab
    ports:
      - 80:80
      - 443:443
      - "22:22"
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/gitlab/etc:/etc/gitlab
      - /data/gitlab/log:/var/log/gitlab
      - /data/gitlab/opt:/var/opt/gitlab
