version: "3.7"

services:
  php:
    build:
      context: .
    container_name: php
    ports:
      - "10022:22"
      - 1080:80
      - 1443:443
      - 19000:9000
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/docker/nginx/logs:/var/log/nginx
      - /data/docker/code:/data/web
