apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-tls
spec:
  secretName: domain-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  dnsNames:
    - "domain.com"
    - "*.domain.com"
  issuerRef:
    name: letsencrypt-prod #letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
