version: "3.7"

networks:
  app_net:
    external: true

services:
  metabase:
    build:
      context: .
    # image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3000:3000
    networks:
      - app_net
    restart: always
    volumes:
      - /data/metabase/metabase-data:/metabase-data
      # - ./plugins:/plugins
      # - type: bind
      #   source: ./plugins
      #   target: /plugins

    environment:
      - TZ=Asia/Shanghai
      - MB_DB_CONNECTION_URI=mysql://mysql:3306/metabase?user=root&password=root
# volumes:
#   metabase-base:
