version: "3.7"

networks:
  app_net:
    external: true

# The default credentials for the web interface are: admin / admin
services:
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    # hostname: cronicle
    ports:
      - 3012:3012
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # - CRONICLE_base_app_url=http://cronicle/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # - /data/docker/cronicle/data:/opt/cronicle/data:rw
      # - /data/docker/cronicle/logs:/opt/cronicle/logs:rw
      # - /data/docker/cronicle/plugins:/opt/cronicle/plugins:rw
      # - /data/docker/cronicle/app:/app:rw
