version: "3.7"

networks:
  app_net:
    external: true

services:
  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    hostname: redis-master
    ports:
      - 16379:6379
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=''
    volumes:
      #   # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/docker/redis-cluster/node1/data:/bitnami/redis/data

  redis-slave-node1:
    image: "bitnami/redis:latest"
    container_name: redis-slave-node1
    hostname: redis-slave-node1
    ports:
      - 16380:6379
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - REDIS_REPLICATION_MODE=slave
      - REDIS_PASSWORD=''
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=''
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/docker/redis-cluster/node1/data:/bitnami/redis/data
    depends_on:
      - redis-master

  redis-slave-node2:
    image: "bitnami/redis:latest"
    container_name: redis-slave-node2
    hostname: redis-slave-node2
    ports:
      - 16381:6379
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - REDIS_REPLICATION_MODE=slave
      - REDIS_PASSWORD=''
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=''
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/docker/redis-cluster/node1/data:/bitnami/redis/data
    depends_on:
      - redis-master

  redis-sentinel1:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel1
    hostname: redis-sentinel1
    ports:
      - "26379:26379"
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=''
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=1000
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/docker/redis-cluster/node1/data:/bitnami/redis/data
    depends_on:
      - redis-master
      - redis-slave-node1
      - redis-slave-node2

  redis-sentinel2:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel2
    hostname: redis-sentinel2
    ports:
      - "26380:26379"
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=''
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=1000
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/docker/redis-cluster/node1/data:/bitnami/redis/data
    depends_on:
      - redis-master
      - redis-slave-node1
      - redis-slave-node2

  redis-sentinel3:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel3
    hostname: redis-sentinel3
    ports:
      - "26381:26379"
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=''
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=1000
    volumes:
      # - ./redis-cluster/node1/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /data/docker/redis-cluster/node1/data:/bitnami/redis/data
    depends_on:
      - redis-master
      - redis-slave-node1
      - redis-slave-node2
