version: "3.7"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  ch1:
    build:
      context: ./clickhouse-server
    container_name: ch1
    hostname: ch1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8124:8123
      - 9001:9000
    networks:
      - backend
    restart: always
    volumes:
      - ./clickhouse-cluster/conf/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-cluster/conf/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-cluster/conf/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      # - ${DATA_PATH}/clickhouse-cluster/ch1/data:/var/lib/clickhouse
      # - ${DATA_PATH}/clickhouse-cluster/ch1/logs:/var/log/clickhouse-server

  ch2:
    build:
      context: ./clickhouse-server
    container_name: ch2
    hostname: ch2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8125:8123
      - 9002:9000
    networks:
      - backend
    restart: always
    volumes:
      - ./clickhouse-cluster/conf/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-cluster/conf/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-cluster/conf/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      # - ${DATA_PATH}/clickhouse-cluster/ch2/data:/var/lib/clickhouse
      # - ${DATA_PATH}/clickhouse-cluster/ch2/logs:/var/log/clickhouse-server

  ch3:
    build:
      context: ./clickhouse-server
    container_name: ch3
    hostname: ch3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8126:8123
      - 9003:9000
    networks:
      - backend
    restart: always
    volumes:
      - ./clickhouse-cluster/conf/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-cluster/conf/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-cluster/conf/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      # - ${DATA_PATH}/clickhouse-cluster/ch3/data:/var/lib/clickhouse
      # - ${DATA_PATH}/clickhouse-cluster/ch3/logs:/var/log/clickhouse-server

  ch4:
    build:
      context: ./clickhouse-server
    container_name: ch4
    hostname: ch4
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8127:8123
      - 9004:9000
    networks:
      - backend
    restart: always
    volumes:
      - ./clickhouse-cluster/conf/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-cluster/conf/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-cluster/conf/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      # - ${DATA_PATH}/clickhouse-cluster/ch3/data:/var/lib/clickhouse
      # - ${DATA_PATH}/clickhouse-cluster/ch3/logs:/var/log/clickhouse-server

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - backend
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
