version: "3.7"

networks:
  bridge-net:
    driver: bridge
# services:
# consul:
#   image: bitnami/consul:latest
#   # container_name: consul
#   ports:
#     - 8300:8300
#     - 8301:8301
#     - 8301:8301/udp
#     - 8500:8500
#     - 8600:8600
#     - 8600:8600/udp
#   networks:
#     - bridge-net
#   restart: always
#   volumes:
#     - ${DATA_PATH}/consul/data:/bitnami

# jaeger:
#   image: jaegertracing/all-in-one:latest
#   # container_name: jaegertracing
#   ports:
#     - 5775:5775/udp
#     - 6831:6831/udp
#     - 6832:6832/udp
#     - 5778:5778
#     - ${JAEGER_PORT}:16686
#     - 14250:14250
#     - 14268:14268
#     - 14269:14269
#     - 9411:9411
#   networks:
#     - bridge-net
#   restart: always
#   environment:
#     COLLECTOR_ZIPKIN_HOST_PORT: 9411

# prometheus:
#   image: bitnami/prometheus:latest
#   # container_name: prometheus
#   ports:
#     - ${PROMETHEUS_PORT}:9090
#   networks:
#     - bridge-net
#   restart: always
#   environment:
#     - TZ=${TIME_ZONE}
#   volumes:
#     - ${DATA_PATH}/prometheus/data:/opt/bitnami/prometheus/data
#     - ${DATA_PATH}/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

# dtm:
#   image: yedf/dtm:latest
#   environment:
#     - TZ=${TIME_ZONE}
#   entrypoint:
#     - "/app/dtm/dtm"
#     - "-c=/app/dtm/configs/config.yaml"
#   ports:
#     - "${DTM_HTTP_PORT}:36789"
#     - "${DTM_GRPC_PORT}:36790"
#   networks:
#     - bridge-net
#   restart: always
#   volumes:
#     - ${DATA_PATH}/dtm/config.yml:/app/dtm/configs/config.yaml
