version: "3.7"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  nginx-master:
    build:
      context: ./nginx-keepalived
    container_name: nginx-master
    hostname: nginx-master
    ports:
      - 10081:80
    networks:
      - backend
    restart: always
    privileged: true
    volumes:
      # - ./nginx-keepalived/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx-keepalived/nginx/conf.d:etc/nginx/conf.d
      - ./nginx-keepalived/nginx/index-master.html:/usr/share/nginx/html/index.html
      - ./nginx-keepalived/keepalived/keepalived-master.conf:/etc/keepalived/keepalived.conf

  nginx-backup:
    build:
      context: ./nginx-keepalived
    container_name: nginx-backup
    hostname: nginx-backup
    ports:
      - 10082:80
    networks:
      - backend
    restart: always
    privileged: true
    volumes:
      # - ./nginx-keepalived/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx-keepalived/nginx/conf.d:etc/nginx/conf.d
      - ./nginx-keepalived/nginx/index-backup.html:/usr/share/nginx/html/index.html
      - ./nginx-keepalived/keepalived/keepalived-backup.conf:/etc/keepalived/keepalived.conf

  # haproxy:
  #   image: haproxy:alpine
  #   container_name: haproxy
  #   hostname: haproxy
  #   ports:
  #     - 18000:8000
  #     - 10080:80
  #   networks:
  #     - backend
  #   restart: always
  #   volumes:
  #     - ./nginx-keepalived/haproxy//haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
