version: "3.7"

networks:
  app_net:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/docker/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /data/docker/grafana/data:/var/lib/grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/:/host:ro,rslave"
