version: "3.7"

networks:
  app_net:
    external: true

services:
  #  http://127.0.0.1:8848/nacos
  #  初始账号密码为 nacos/nacos
  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: nacos
    ports:
      - 8848:8848
      - 9848:9848
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - NACOS_APPLICATION_PORT=8848
      # - SPRING_DATASOURCE_PLATFORM=mysql
      # - MYSQL_SERVICE_HOST=mysql
      # - MYSQL_SERVICE_PORT=3306
      # - MYSQL_SERVICE_USER=root
      # - MYSQL_SERVICE_PASSWORD=123456
      # - MYSQL_SERVICE_DB_NAME=nacos_config
      - JVM_XMS=256m
      - JVM_XMX=256m
    volumes:
      - /data/nacos/logs:/home/nacos/logs
      # - /data/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
