version: "3.7"

networks:
  app_net:
    external: true

services:
  node:
    build:
      context: .
    working_dir: /data
    container_name: node
    ports:
      - 3000:3000
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data:/data
    stdin_open: true
    tty: true
