# https://raw.githubusercontent.com/containous/traefik/master/traefik.sample.yml

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  fields:
    names:
      StartLocal: keep
      StartUTC: drop

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: :80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: https

  https:
    address: :443
    # http:
    #   tls: {}

  traefik:
    address: :8080

  metrics:
    address: :8082

  # mysql:
  #   address: :3306

  # redis:
  #   address: :6379

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    watch: true
    directory: /data/traefik/config

metrics:
  prometheus:
    entryPoint: metrics
