# HTTP 代理端口
#port: 7890

# SOCKS5 代理端口
#socks-port: 7891

# 混合代理端口
mixed-port: 7890

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Global（全局代理）/ Rule（规则） / Script(腳本) / Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: "0.0.0.0:9090"

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
external-ui: /ui

# RESTful API 的口令 (可选)
secret: ""

# DNS 设置
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
    - 119.29.29.29 # DNSpod DNS 17ms
    - 223.5.5.5 # 阿里 19ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
    - tls://8.8.8.8:853 # Google DNS over TLS
    - tls://8.8.4.4:853 # cloudflare DNS over TLS
    - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
    - https://dns.google/dns-query # Google DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
      - 240.0.0.0/4

# 代理节点
proxy-providers:
  # provider_file:
  #   type: file
  #   path: ./provider_local.yaml
  #   health-check:
  #     enable: true
  #     interval: 600
  #     url: https://www.gstatic.com/generate_204

  # v2rayshare:
  #   type: http
  #   path: ./v2rayshare.yaml
  #   url: https://v2rayshare.com/wp-content/uploads/2023/01/20230127.yaml # 订阅地址
  #   interval: 86400
  #   health-check:
  #     enable: true
  #     interval: 600
  #     # lazy: true
  #     url: https://www.gstatic.com/generate_204

  paimonnode:
    type: http
    path: ./paimonnode.yaml
    url: https://sub.pmsub.me/clash.yaml
    interval: 7200
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://www.gstatic.com/generate_204

  # tbbatbb:
  #   type: http
  #   path: ./tbbatbb.yaml
  #   url: https://raw.githubusercontent.com/tbbatbb/Proxy/master/dist/clash.config.yaml
  #   interval: 7200
  #   health-check:
  #     enable: true
  #     interval: 600
  #     # lazy: true
  #     url: https://www.gstatic.com/generate_204

  # sub:
  #   type: http
  #   path: ./sub.yaml
  #   url: https://cdn.jsdelivr.net/gh/anaer/Sub@main/clash.yaml
  #   interval: 7200
  #   health-check:
  #     enable: true
  #     interval: 600
  #     # lazy: true
  #     url: https://www.gstatic.com/generate_204

  free_proxy_ss:
    type: http
    path: ./free_proxy_ss.yaml
    url: https://cdn.jsdelivr.net/gh/learnhard-cn/free_proxy_ss@main/clash/clash.provider.yaml
    interval: 7200
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://www.gstatic.com/generate_204

  subscribe:
    type: http
    path: ./free_proxy_ss.yaml
    url: https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
    interval: 7200
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: https://www.gstatic.com/generate_204

# 代理组策略
proxy-groups:
  - name: PROXY
    type: select # load-balance, select, relay, fallback, url-test
    use:
      #   - v2rayshare
      - paimonnode
      # - tbbatbb
      - free_proxy_ss
      # - sub
      - subscribe
    proxies:
      # - ♻️ 自动选择
      - DIRECT
      - ⚖️ 负载均衡-轮询
      - ⚖️ 负载均衡-散列

  - name: ⚖️ 负载均衡-轮询
    type: load-balance
    url: https://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    use:
      - paimonnode

  - name: ⚖️ 负载均衡-散列
    type: load-balance
    url: https://www.gstatic.com/generate_204
    interval: 300
    strategy: consistent-hashing
    use:
      - paimonnode

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

# 白名单模式 Rules 配置方式（推荐）
# rules:
#   - RULE-SET,applications,DIRECT
#   - DOMAIN,clash.razord.top,DIRECT
#   - DOMAIN,yacd.haishan.me,DIRECT
#   - RULE-SET,private,DIRECT
#   - RULE-SET,reject,REJECT
#   - RULE-SET,icloud,DIRECT
#   - RULE-SET,apple,DIRECT
#   - RULE-SET,google,DIRECT
#   - RULE-SET,proxy,PROXY
#   - RULE-SET,direct,DIRECT
#   - RULE-SET,lancidr,DIRECT
#   - RULE-SET,cncidr,DIRECT
#   - RULE-SET,telegramcidr,PROXY
#   - GEOIP,LAN,DIRECT
#   - GEOIP,CN,DIRECT
#   - MATCH,PROXY

# 黑名单模式 Rules 配置方式
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
