version: "3.7"

networks:
  app_net:
    external: true

# localhost:9090/ui
services:
  clash:
    # image: dreamacro/clash:latest
    image: dreamacro/clash-premium:latest
    container_name: clash
    ports:
      - 7890:7890
      - 7891:7891
      - 9090:9090 # external controller (Restful API)
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./Country.mmdb:/root/.config/clash/Country.mmdb
      - ./ruleset:/root/.config/clash/ruleset
      - ./config.yaml:/root/.config/clash/config.yaml
      - ./ui:/ui # dashboard volume
    # # TUN
    # cap_add:
    #   - NET_ADMIN
    # devices:
    #   - /dev/net/tun

  yacd:
    image: haishanh/yacd:latest
    container_name: yacd
    ports:
      - 1234:80
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
