version: "3.7"

networks:
  app_net:
    external: true

services:
  minio1:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - 9001:9000
      - 9091:9090
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=123456
      # - MINIO_SERVER_URL=
      # - MINIO_BROWSER_REDIRECT_URL=
    volumes:
      - /data/minio1/data1:/data1
      - /data/minio1/data2:/data2
    command: server --console-address ":9090" http://minio{1...3}/data{1...2}

  minio2:
    image: quay.io/minio/minio
    container_name: minio2
    ports:
      - 9002:9000
      - 9092:9090
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=123456
    volumes:
      - /data/minio2/data1:/data1
      - /data/minio2/data2:/data2
    command: server --console-address ":9090" http://minio{1...3}/data{1...2}

  minio3:
    image: quay.io/minio/minio
    container_name: minio3
    ports:
      - 9003:9000
      - 9093:9090
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=123456
    volumes:
      - /data/minio3/data1:/data1
      - /data/minio3/data2:/data2
    command: server --console-address ":9090" http://minio{1...3}/data{1...2}

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 9000:9000
      - 9090:9090
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/logs:/var/log/nginx
