version: "3.7"

networks:
  app_net:
    external: true

services:
  pxc-node1:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pxc-node1
    hostname: pxc-node1
    ports:
      - 13306:3306
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - CLUSTER_NAME=PXC
      - XTRABACKUP_PASSWORD=pxc123
    volumes:
      # - ./pxc/node1/conf:/etc/mysql/conf.d
      - /data/docker/pxc/node1/data:/var/lib/mysql
      - /data/docker/pxc/node1/logs:/var/log/mysql

  pxc-node2:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pxc-node2
    hostname: pxc-node2
    ports:
      - 13307:3306
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - CLUSTER_NAME=PXC
      - XTRABACKUP_PASSWORD=pxc123
      - CLUSTER_JOIN=pxc-node1
    volumes:
      # - ./pxc/node2/conf:/etc/mysql/conf.d
      - /data/docker/pxc/node2/data:/var/lib/mysql
      - /data/docker/pxc/node2/logs:/var/log/mysql
    depends_on:
      - pxc-node1

  pxc-node3:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pxc-node3
    hostname: pxc-node3
    ports:
      - 13308:3306
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - CLUSTER_NAME=PXC
      - XTRABACKUP_PASSWORD=pxc123
      - CLUSTER_JOIN=pxc-node1
    volumes:
      # - ./pxc/node3/conf:/etc/mysql/conf.d
      - /data/docker/pxc/node3/data:/var/lib/mysql
      - /data/docker/pxc/node3/logs:/var/log/mysql
    depends_on:
      - pxc-node1
