version: "3.7"

networks:
  app_net:
    external: true

services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - /data/prometheus/data:/opt/bitnami/prometheus/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/grafana/data:/var/lib/grafana
