version: "3.7"

networks:
  app_net:
    external: true

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=lalifeir
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - /data/mysql/data:/var/lib/mysql
      - /data/mysql/logs:/var/log/mysql

  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - network.bind_host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false

  kibana:
    image: kibana:7.17.6
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  canal-server:
    image: canal/canal-server:v1.1.6
    container_name: canal-server
    ports:
      - 11111:11111
      - 11110:11110
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - canal.auto.scan=false
      - canal.destinations=test
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.instance.filter.regex=.*\\..*
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.instance.gtidon=false
      - canal.admin.manager=canal-admin:8089
      - canal.admin.port=11110
      - canal.admin.user=admin
      # select password('123456');
      # mysql8.0 select upper(sha1(unhex(sha1('123456'))))
      - canal.admin.passwd=6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
      # - canal.admin.register.cluster=test
    volumes:
      # - ./canal-server/conf:/home/admin/canal-server/conf
      - /data/canal-server/logs:/home/admin/canal-server/logs
    depends_on:
      - canal-admin

  canal-adapter:
    # image: slpcat/canal-adapter:v1.1.5
    build:
      context: ./canal-adapter
    container_name: canal-adapter
    ports:
      - 8081:8081
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # - ./canal-adapter/conf/application.yml:/opt/canal/adapter/conf/application.yml
      - ./canal-adapter/conf:/opt/canal/adapter/conf
    depends_on:
      - canal-server

  canal-admin:
    image: canal/canal-admin:v1.1.6
    container_name: canal-admin
    ports:
      - 8089:8089
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - server.port=8089
      - canal.adminUser=admin
      - canal.adminPasswd=123456
      - spring.datasource.address=mysql:3306
      - spring.datasource.database=canal_manager
      - spring.datasource.username=root
      - spring.datasource.password=canal
      - mysql
    depends_on:
      - mysql
