[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["lalifeier <lalifeier@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.86.0"
uvicorn = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
