version: "3.7"

networks:
  app_net:
    external: true

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 18123:8123
      - 19000:9000
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - /data/docker/clickhouse-server/data:/var/lib/clickhouse
      - /data/docker/clickhouse-server/logs:/var/log/clickhouse-server
