version: "3.7"

networks:
  app_net:
    external: true

services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    ports:
      - 1080:80
      - 1443:443
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - /data/openresty/logs:/var/log/nginx
      - /code:/var/www/html
