# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   containers:
#     - name: nginx
#       image: nginx:alpine
#       ports:
#         - containerPort: 80
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-server
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
  namespace: kube-server
# spec:
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#   selector:
#     app: nginx-deployment
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32351
  selector:
    app: nginx-deployment
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#   selector:
#     app: nginx-deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: kube-server
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod" #letsencrypt-staging
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  # ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - test.domain.com
  #     secretName: test.domain.com-tls

  rules:
    - host: nginx.domain.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
