version: "3.7"

networks:
  app_net:
    external: true

services:
  seata-server:
    image: seataio/seata-server:1.6.1
    container_name: seata-server
    ports:
      - 8091:8091
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - STORE_MODE=file
      # - SEATA_IP=127.0.0.1
      - SEATA_PORT=8091
    # volumes:
    # - ./registry.conf:/seata-server/resources/registry.conf
