version: "3.7"

networks:
  app_net:
    external: true

services:
  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./elasticsearch/cert/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
      - /data/elasticsearch/plugins:/usr/share/elasticsearch/plugins

  skywalking-oap:
    image: skywalking-oap-server:latest
    container_name: skywalking-oap
    ports:
      - 11800:11800
      - 12800:12800
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    # volumes:
    # - ./skywalking/config/alarm-settings.yml:/skywalking/config/alarm-settings.yml
    # - ./skywalking/ext-config:/skywalking/ext-config
    depends_on:
      - elasticsearch

  skywalking-ui:
    image: apache/skywalking-ui:latest
    container_name: skywalking-ui
    ports:
      - 8088:8080
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SW_OAP_ADDRESS=skywalking-oap:12800
    depends_on:
      - skywalking-oap
