version: "3.7"

networks:
  app_net:
    external: true

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo/db:/data/db
      - /data/mongo/log:/var/log/mongodb
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
