version: "3.7"

networks:
  app_net:
    external: true

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - 8081:8081
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/docker/nexus:/nexus-data
