version: "3.7"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8989:8080
      - 50000:50000
    networks:
      - backend
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/jenkins/jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
