version: "3.7"

networks:
  bridge-net:
    driver: bridge

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8989:8080
      - 50000:50000
    networks:
      - bridge-net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/jenkins/jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
