version: "3.7"

networks:
  app_net:
    external: true

services:
  # es-node1:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
  #   container_name: es-node1
  #   ports:
  #     - 19200:9200
  #     - 19300:9300
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - ES_JAVA_OPTS=-Xmx256m -Xms256m
  #     # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-}
  #   volumes:
  #     - ./es-node1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #     # - ./es-node1/cert/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
  #     - /data/elk/es-node1/data:/usr/share/elasticsearch/data
  #     - /data/elk/es-node1/logs:/usr/share/elasticsearch/logs
  #     - /data/elk/es-node1/plugins:/usr/share/elasticsearch/plugins

  # es-node2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
  #   container_name: es-node2
  #   ports:
  #     - 19201:9200
  #     - 19301:9300
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - ES_JAVA_OPTS=-Xmx256m -Xms256m
  #   volumes:
  #     - ./es-node2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #     # - ./es-node2/cert/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
  #     - /data/elk/es-node2/data:/usr/share/elasticsearch/data
  #     - /data/elk/es-node2/logs:/usr/share/elasticsearch/logs
  #     - /data/elk/es-node2/plugins:/usr/share/elasticsearch/plugins

  # es-node3:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
  #   container_name: es-node3
  #   ports:
  #     - 19202:9200
  #     - 19302:9300
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - ES_JAVA_OPTS=-Xmx256m -Xms256m
  #   volumes:
  #     - ./es-node3/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #     # - ./es-node3/cert/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
  #     - /data/elk/es-node3/data:/usr/share/elasticsearch/data
  #     - /data/elk/es-node2/logs:/usr/share/elasticsearch/logs
  #     - /data/elk/es-node3/plugins:/usr/share/elasticsearch/plugins

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      # - discovery.type=single-node
      # - ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    # volumes:
    # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # - ./elasticsearch/cert/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    # - /data/elk/elasticsearch/data:/usr/share/elasticsearch/data
    # - /data/elk/elasticsearch/logs:/usr/share/elasticsearch/logs
    # - /data/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=kibana_system
      # - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
  #   container_name: logstash
  #   ports:
  #     - 5044:5044
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - LS_JAVA_OPTS=-Xmx256m -Xms256m
  #     # - LOGSTASH_INTERNAL_PASSWORD=${LOGSTASH_PASSWORD:-}
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #     - /data/elk/logstash/data:/usr/share/logstash/data
  #   depends_on:
  #     - elasticsearch

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
  #   container_name: filebeat
  #   ports:
  #     - 5044:5044
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #     # ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - /data/elk/filebeat/data:/usr/share/filebeat/data
  #     - /data/elk/filebeat/log:/usr/share/filebeat/log
  #   depends_on:
  #     - elasticsearch
