server.name: kibana
server.host: 0.0.0.0
server.port: 5601
# elasticsearch.hosts:
#   ["http://es-node1:9200", "http://es-node2:9200", "http://es-node3:9200"]
elasticsearch.hosts: ["http://elasticsearch:9200"]
# elasticsearch.username: "elastic"
# elasticsearch.password: ${KIBANA_PASSWORD}
monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: "zh-CN"
