filebeat.inputs:
  - type: log
    enabled: true
    paths:
      #   - /var/log/nginx/access.log
      - /var/lib/docker/containers/*/*-json.log
    fields:
      # source: nginx-access
      source: log

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# output.console:
#   pretty: true

output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  topic: "elk-%{[fields.source]}"
  partition.round_robin:
    reachable_only: true
  compression: gzip
  max_message_bytes: 1000000
  required_acks: 1
