version: "3.7"

# https://github.com/P3TERX/Aria2-Pro-Docker/blob/master/docker-compose.yml

networks:
  app_net:
    external: true

services:
  aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    networks:
      - app_net
    restart: always
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /data/aria2/downloads:/downloads

  ariang:
    container_name: ariang
    image: p3terx/ariang
    networks:
      - app_net
    ports:
      - 6880:6880
    restart: always
