version: "3.7"

networks:
  bridge-net:
    driver: bridge

services:
  python:
    build:
      context: .
    working_dir: /code
    container_name: python
    ports:
      - 5000:5000
    networks:
      - bridge-net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /code:/code
    stdin_open: true
    tty: true
