version: "3.7"

networks:
  app_net:
    external: true

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - /data/docker/redis/data:/data
