version: "3.7"

networks:
  app_net:
    external: true

services:
  mysql:
    build:
      context: .
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=lalifeir
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    # command:
    #   --default-authentication-plugin=mysql_native_password
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_general_ci
    #   --explicit_defaults_for_timestamp=true
    #   --lower_case_table_names=1
    volumes:
      - ./conf:/etc/mysql/conf.d
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/logs:/var/log/mysql
