version: "3.7"

networks:
  app_net:
    external: true

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    hostname: haproxy
    ports:
      - 8888:8888
    networks:
      - app_net
    restart: always
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
