version: "3.7"

networks:
  app_net:
    external: true

services:
  # fluent-bit:
  #   image: fluent/fluent-bit:latest
  #   container_name: fluent-bit
  #   ports:
  #     - 24224:24224
  #   networks:
  #     - app_net
  #   restart: always
  #   environment:
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - ./conf/:/etc/fluent-bit/:ro
  #     - ./fluentd/etc/fluent.conf:/fluentd/etc/fluent.conf
  #     # - ./fluentd/etc:/fluentd/etc
  #     - /data/fluentd/log:/fluentd/log
  #   command:
  #     - /fluent-bit/bin/fluent-bit
  #     - --config=/etc/fluent-bit/fluent-bit.conf

  fluentd:
    image: fluentd:latest
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./fluentd/etc/fluent.conf:/fluentd/etc/fluent.conf
      # - ./fluentd/etc:/fluentd/etc
      - /data/fluentd/log:/fluentd/log

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 1080:80
      - 1443:443
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 9999:9999
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 允许使用PLAINTEXT协议(镜像中默认为关闭,需要手动开启)
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      # 关闭自动创建 topic 功能
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 全局消息过期时间 6 小时(测试时可以设置短一点)
      # - KAFKA_CFG_LOG_RETENTION_HOURS=6
      # 开启JMX监控
      - JMX_PORT=9999
      # - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9999
    # volumes:
    #   - /data/kafka:/bitnami/kafka
    depends_on:
      - zookeeper

  efak:
    image: nickzurich/kafka-eagle:3.0.1
    container_name: efak
    ports:
      - 8048:8048
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - EFAK_CLUSTER_ZK_LIST=zookeeper:2181
    depends_on:
      - kafka

  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - network.bind_host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false

  kibana:
    image: kibana:7.17.6
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
