server.name: kibana
server.host: 0.0.0.0
server.port: 5601
elasticsearch.hosts: ["http://elasticsearch:9200"]
# elasticsearch.username: ${ELASTICSEARCH_USERNAME}

elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: "zh-CN"
