version: "3.7"

networks:
  app_net:
    external: true

services:
  # config server: config-server1 ~ config-server3
  mongo-config-server1:
    image: mongo:latest
    container_name: mongo-config-server1
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./config-server/conf:/etc/mongo
      # - /data/mongo/sharded/config/server1/db:/data/db
      # - /data/mongo/sharded/config/server1/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongo-config-server2:
    image: mongo:latest
    container_name: mongo-config-server2
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./config-server/conf:/etc/mongo
      # - /data/mongo/sharded/config/server2/db:/data/db
      # - /data/mongo/sharded/config/server2/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongo-config-server3:
    image: mongo:latest
    container_name: mongo-config-server3
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./config-server/conf:/etc/mongo
      # - /data/mongo/sharded/config/server3/db:/data/db
      # - /data/mongo/sharded/config/server3/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  # shard server Shard1: sh1r1 ~ sh1r3
  mongo-shard1-server1:
    image: mongo:latest
    container_name: mongo-shard1-server1
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./shard1-server/conf:/etc/mongo
      # - /data/mongo/sharded/shard1/server1/db:/data/db
      # - /data/mongo/sharded/shard1/server1/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongo-shard1-server2:
    image: mongo:latest
    container_name: mongo-shard1-server2
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./shard1-server/conf:/etc/mongo
      # - /data/mongo/sharded/shard1/server2/db:/data/db
      # - /data/mongo/sharded/shard1/server2/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongo-shard1-server3:
    image: mongo:latest
    container_name: mongo-shard1-server3
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./shard1-server/conf:/etc/mongo
      # - /data/mongo/sharded/shard1/server3/db:/data/db
      # - /data/mongo/sharded/shard1/server3/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  # shard server Shard2: sh2r1 ~ sh2r3
  mongo-shard2-server1:
    image: mongo:latest
    container_name: mongo-shard2-server1
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./shard2-server/conf:/etc/mongo
      # - /data/mongo/sharded/shard2/server1/db:/data/db
      # - /data/mongo/sharded/shard2/server1/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongo-shard2-server2:
    image: mongo:latest
    container_name: mongo-shard2-server2
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./shard2-server/conf:/etc/mongo
      # - /data/mongo/sharded/shard2/server2/db:/data/db
      # - /data/mongo/sharded/shard2/server2/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongo-shard2-server3:
    image: mongo:latest
    container_name: mongo-shard1-server3
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./shard2-server/conf:/etc/mongo
      # - /data/mongo/sharded/shard2/server3/db:/data/db
      # - /data/mongo/sharded/shard2/server3/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  # router
  mongos-server1:
    image: mongo:latest
    container_name: mongos-server
    ports:
      - 37017:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongos-server/conf:/etc/mongo
      # - /data/mongo/sharded/mongos/server1/db:/data/db
      # - /data/mongo/sharded/mongos/server1/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongos-server2:
    image: mongo:latest
    container_name: mongos-server
    ports:
      - 37018:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongos-server/conf:/etc/mongo
      # - /data/mongo/sharded/mongos/server2/db:/data/db
      # - /data/mongo/sharded/mongos/server2/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf

  mongos-server3:
    image: mongo:latest
    container_name: mongos-server
    ports:
      - 37019:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_DATABASE=test
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGO_USERNAME=user
      # - MONGO_PASSWORD=123456
    volumes:
      # - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongos-server/conf:/etc/mongo
      # - /data/mongo/sharded/mongos/server3/db:/data/db
      # - /data/mongo/sharded/mongos/server3/log:/var/log/mongodb
    command: mongod --config /etc/mongo/mongo.conf
