version: "3.7"

networks:
  app_net:
    external: true

services:
  # config server: config1 ~ config3
  mongo-config1:
    image: mongo:latest
    container_name: mongo-config1
    ports:
      - 27031:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-config1/db:/data/db
      # - /data/mongo-config1/log:/var/log/mongodb
    command: mongod --configsvr --replSet Config --config /etc/mongo/mongod.conf

  mongo-config2:
    image: mongo:latest
    container_name: mongo-config1
    ports:
      - 27032:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-config2/db:/data/db
      # - /data/mongo-config2/log:/var/log/mongodb
    command: mongod --configsvr --replSet Config --config /etc/mongo/mongod.conf

  mongo-config3:
    image: mongo:latest
    container_name: mongo-config1
    ports:
      - 27033:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-config3/db:/data/db
      # - /data/mongo-config3/log:/var/log/mongodb
    command: mongod --configsvr --replSet Config --config /etc/mongo/mongod.conf

  # shard server Shard1: sh1r1 ~ sh1r3
  mongo-sh1r1:
    image: mongo:latest
    container_name: mongo-sh1r1
    ports:
      - 27041:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-sh1r1/db:/data/db
      # - /data/mongo-sh1r1/log:/var/log/mongodb
    command: mongod --replSet Shard1 --config /etc/mongo/mongod.conf

  mongo-sh1r2:
    image: mongo:latest
    container_name: mongo-sh1r2
    ports:
      - 27042:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-sh1r2/db:/data/db
      # - /data/mongo-sh1r2/log:/var/log/mongodb
    command: mongod --replSet Shard1 --config /etc/mongo/mongod.conf

  mongo-sh1r3:
    image: mongo:latest
    container_name: mongo-sh1r3
    ports:
      - 27043:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-sh1r3/db:/data/db
      # - /data/mongo-sh1r3/log:/var/log/mongodb
    command: mongod --replSet Shard1 --config /etc/mongo/mongod.conf

  # shard server Shard2: sh2r1 ~ sh2r3
  mongo-sh2r1:
    image: mongo:latest
    container_name: mongo-sh2r1
    ports:
      - 27051:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-sh2r1/db:/data/db
      # - /data/mongo-sh2r1/log:/var/log/mongodb
    command: mongod --replSet Shard2 --config /etc/mongo/mongod.conf

  mongo-sh2r2:
    image: mongo:latest
    container_name: mongo-sh2r2
    ports:
      - 27052:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-sh2r2/db:/data/db
      # - /data/mongo-sh2r2/log:/var/log/mongodb
    command: mongod --replSet Shard2 --config /etc/mongo/mongod.conf

  mongo-sh2r3:
    image: mongo:latest
    container_name: mongo-sh1r3
    ports:
      - 27053:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-sh2r3/db:/data/db
      # - /data/mongo-sh2r3/log:/var/log/mongodb
    command: mongod --replSet Shard2 --config /etc/mongo/mongod.conf

  # router
  mongo-router:
    image: mongo:latest
    container_name: mongo-router
    ports:
      - 27053:27017
    networks:
      - app_net
    restart: always
    # privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=123456
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./conf:/etc/mongo
      - /data/mongo-router/db:/data/db
      # - /data/mongo-router/log:/var/log/mongodb
    command: mongod -configdb Config/mongo-config1:27031,mongo-config2:27032,mongo-config3:27033 --config /etc/mongo/mongod.conf
