version: "3.7"

networks:
  app_net:
    external: true

services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - 9092:9092
      # - 9999:9999
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # - KAFKA_BROKER_ID=1
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - JMX_PORT=9999
    # volumes:
    #   - ${DATA_PATH}/kafka/data:/bitnami/kafka/data
    #   - ${DATA_PATH}/kafka/config:/bitnami/kafka/config
    # depends_on:
    #   - zookeeper

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    # volumes:
    #   - ./zookeeper/conf/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
    #   - ${DATA_PATH}/zookeeper/data:/bitnami/zookeeper/data

  efak:
    build:
      context: ../efak
    container_name: efak
    ports:
      - 8048:8048
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ZK_HOSTS=zookeeper:2181
    volumes:
      - ../efak/conf/system-config.properties:/usr/local/efak/conf/system-config.properties
      - /data/efak/logs:/usr/local/efak/logs
    depends_on:
      - zookeeper
      - kafka
    stdin_open: true
    tty: true
