version: "3.7"

networks:
  app_net:
    external: true

# user: demo
# password: 123456

services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - 4873:4873
    networks:
      - app_net
    restart: always
    environment:
      - TZ=Asia/Shanghai
      # - VERDACCIO_PORT=4873
    volumes:
      - ./conf:/verdaccio/conf
      - /data/docker/verdaccio/storage:/verdaccio/storage
      - /data/docker/verdaccio/plugins:/verdaccio/plugins
