version: "3.7"

networks:
  bridge-net:
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - bridge-net
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - /data/redis/data:/data
