version: "3.7"

networks:
  app_net:
    external: true

services:
  drone:
    image: drone/drone:latest
    container_name: drone
    ports:
      - 80:80
      - 443:443
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - DRONE_GITEA_SERVER=https://gitea.com
      - DRONE_GITEA_CLIENT_ID=change-to-your-gitea-client-id
      - DRONE_GITEA_CLIENT_SECRET=change-to-your-gitea-client-secret
      - DRONE_RPC_SECRET=change-to-your-shared-secret
      - DRONE_SERVER_HOST=drone.gitea.io
      - DRONE_SERVER_PROTO=https
    volumes:
      - /data/drone/data:/data

  drone-runner:
    image: drone/drone-runner-docker:latest
    container_name: runner
    ports:
      - 3000:3000
    networks:
      - app_net
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=drone.gitea.io
      - DRONE_RPC_SECRET=change-to-your-shared-secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
